/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home_account: () => import("@/views/home/account/index.vue"),
  home_course: () => import("@/views/home/course/index.vue"),
  "home_homework-records-detail": () => import("@/views/home/homework-records-detail/index.vue"),
  "home_homework-records": () => import("@/views/home/homework-records/index.vue"),
  home_homework: () => import("@/views/home/homework/index.vue"),
  "home_problem-detail": () => import("@/views/home/problem-detail/index.vue"),
  "home_problem-list": () => import("@/views/home/problem-list/index.vue"),
  home_records: () => import("@/views/home/records/index.vue"),
  "home_submission-detail": () => import("@/views/home/submission-detail/index.vue"),
};
