/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export const generatedRoutes: any[] = [{
  name: '403',
  path: '/403',
  component: 'layout.blank$view.403',
  meta: {
    title: '403',
    i18nKey: 'route.403',
    constant: true
  }
}, {
  name: '404',
  path: '/404',
  component: 'layout.blank$view.404',
  meta: {
    title: '404',
    i18nKey: 'route.404',
    constant: true
  }
}, {
  name: '500',
  path: '/500',
  component: 'layout.blank$view.500',
  meta: {
    title: '500',
    i18nKey: 'route.500',
    constant: true
  }
}, {
  name: 'home',
  path: '/home',
  component: 'layout.base',
  meta: {
    title: 'home',
    i18nKey: 'route.home'
  },
  children: [{
    name: 'home_account',
    path: '/home/account',
    component: 'view.home_account',
    meta: {
      title: 'home_account',
      i18nKey: 'route.home_account'
    }
  }, {
    name: 'home_course',
    path: '/home/course',
    component: 'view.home_course',
    meta: {
      title: 'home_course',
      i18nKey: 'route.home_course'
    }
  }, {
    name: 'home_homework',
    path: '/home/homework',
    component: 'view.home_homework',
    meta: {
      title: 'home_homework',
      i18nKey: 'route.home_homework'
    }
  }, {
    name: 'home_homework-records',
    path: '/home/homework-records',
    component: 'view.home_homework-records',
    meta: {
      title: 'home_homework-records',
      i18nKey: 'route.home_homework-records'
    }
  }, {
    name: 'home_homework-records-detail',
    path: '/home/homework-records-detail',
    component: 'view.home_homework-records-detail',
    meta: {
      title: 'home_homework-records-detail',
      i18nKey: 'route.home_homework-records-detail'
    }
  }, {
    name: 'home_problem-detail',
    path: '/home/problem-detail',
    component: 'view.home_problem-detail',
    meta: {
      title: 'home_problem-detail',
      i18nKey: 'route.home_problem-detail'
    }
  }, {
    name: 'home_problem-list',
    path: '/home/problem-list',
    component: 'view.home_problem-list',
    meta: {
      title: 'home_problem-list',
      i18nKey: 'route.home_problem-list'
    }
  }, {
    name: 'home_records',
    path: '/home/records',
    component: 'view.home_records',
    meta: {
      title: 'home_records',
      i18nKey: 'route.home_records'
    }
  }, {
    name: 'home_submission-detail',
    path: '/home/submission-detail',
    component: 'view.home_submission-detail',
    meta: {
      title: 'home_submission-detail',
      i18nKey: 'route.home_submission-detail'
    }
  }]
}, {
  name: 'login',
  path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
  component: 'layout.blank$view.login',
  props: true,
  meta: {
    title: 'login',
    i18nKey: 'route.login',
    constant: true
  }
}];
